apiVersion: apps/v1
kind: Deployment
metadata:
  name: raining-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raining-processor
  template:
    metadata:
      labels:
        app: raining-processor
    spec:
      containers:
        - name: raining-processor
          image: raining-processor:1.1
          imagePullPolicy: IfNotPresent
