apiVersion: v1
kind: Service
metadata:
  name: weather-station
spec:
  clusterIP: None
  selector:
    app: weather-station
  ports:
    - port: 9092

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weather-station
spec:
  serviceName: weather-station
  replicas: 10
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      containers:
        - name: weather-station
          image: weather-station:1.0
          imagePullPolicy: IfNotPresent